# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs
jobs:
  checkout-deps-install:
    macos:
      xcode: 11.3.0
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          name: Restore brew deps
          keys:
            - brew-deps
      - run:
          name: Install brew deps
          command: brew install ffmpeg coreutils
      - run:
          name: Do not upgrade node and yarn
          command: brew pin yarn node
      - save_cache:
          name: Save brew deps to cache
          key: brew-deps
          paths:
            - /usr/local/Cellar
            - /usr/local/Homebrew
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install node deps
          command: yarn install --immutable
      - run:
          name: Install gulp node deps
          command: cd gulp && yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  unsigned-osx-build:
    macos:
      xcode: 11.3.0
    resource_class: large
    steps:
      - run:
          name: Run the build
          command: cd gulp && gulp standalone.package.prod.darwin64.unsigned
workflows:
  # Name the workflow "welcome"
  unsigned-osx:
    jobs:
      - checkout-deps-install
      - unsigned-osx-build:
          requires:
            - checkout-deps-install